[package]
name = "newest_of"
version = "1.0.0"
authors = ["nmaeda <nmaeda@keepdata.asia>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
structopt = "0.3"
